apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: log-server
  name: log-server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: log-server
    spec:
      restartPolicy: Always
      volumes:
       - name: secrets-cloudsql
         secret:
           secretName: cloudsql
      containers:
      - name: trillian-logserver
        args: [
        "--mysql_uri=test:zaphod@tcp(127.0.0.1:3306)/test",
        "--rpc_endpoint=0.0.0.0:8090",
        "--http_endpoint=0.0.0.0:8091",
        "--alsologtostderr"
        ]
        image: gcr.io/trillian-opensource-ci/log_server:latest
        livenessProbe:
         httpGet:
           path: /metrics
           port: 8091
        name: log-server
        ports:
        - containerPort: 8090
        - containerPort: 8091
        resources: {}
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.16
        command: ["/cloud_sql_proxy",
                  "-instances=key-transparency:us-central1:keytransparency-sandbox=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: secrets-cloudsql
            mountPath: /secrets/cloudsql
            readOnly: true
status: {}
