apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../../docker-compose.yml
    kompose.service.type: LoadBalancer
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      volumes:
       - name: secrets
         secret:
           secretName: kt-secrets
      containers:
      - command:
        - /keytransparency-server
        - --addr=0.0.0.0:8080
        - --db=test:zaphod@tcp(db:3306)/test
        - --log-url=log-server:8090
        - --map-url=map-server:8090
        - --tls-key=/run/secrets/server.key
        - --tls-cert=/run/secrets/server.crt
        - --auth-type=insecure-fake
        - --alsologtostderr
        - --v=5
        image: gcr.io/key-transparency/keytransparency-server:latest
        livenessProbe:
         httpGet:
           path: /metrics
           port: 8081
        name: server
        ports:
        - containerPort: 8080
        - containerPort: 8081
        resources: {}
        volumeMounts:
        - name: secrets
          mountPath: "/run/secrets"
          readOnly: true
      restartPolicy: Always
status: {}
