apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      volumes:
       - name: secrets
         secret:
           secretName: kt-tls
      containers:
      - command:
        - /keytransparency-server
        - --addr=0.0.0.0:8080
        - --db=test:zaphod@tcp(db:3306)/test
        - --log-url=log-server:8090
        - --map-url=map-server:8090
        - --tls-key=/run/secrets/tls.key
        - --tls-cert=/run/secrets/tls.crt
        - --auth-type=insecure-fake
        - --alsologtostderr
        - --v=5
        image: gcr.io/key-transparency/keytransparency-server:latest
        livenessProbe:
         httpGet:
           path: /healthz
           port: 8081
        readinessProbe:
         httpGet:
           path: /readyz
           port: 8081
        name: server
        ports:
        - containerPort: 8080
        - containerPort: 8081
        resources: {}
        volumeMounts:
        - name: secrets
          mountPath: "/run/secrets"
          readOnly: true
      restartPolicy: Always
status: {}
