version: ~> 1.0
language: go
go:
- "1.13.x"
dist: bionic

go_import_path: github.com/google/keytransparency

services:
- docker
- mysql
cache:
  directories:
  - "$HOME/gcloud/"
  - "$HOME/gopath/pkg/mod"
env:
  global:
  - PATH=$PATH:${HOME}/google-cloud-sdk/bin
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - GO111MODULE=on

jobs:
  include:
    - name: "build"
      script: go build ./...
    - name: "lint"
      install: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.19.0
      script: golangci-lint run --deadline=7m
    - name: "coverage"
      script:
      - go test ./... -v -coverprofile=coverage1.txt
      - go test ./impl/integration/ -v -coverprofile=coverage2.txt -coverpkg=./...
      after_success: bash <(curl -s https://codecov.io/bash)
    - name: "race"
      script:
      - go test -race ./... -v
    - name: "docker integration test"
      install: skip
      script: ./scripts/integration.sh
    - stage: deploy
      if: branch = master AND type != pull_request
      install:
      - gcloud -q components install kubectl
      - openssl aes-256-cbc -K $encrypted_555d9b2948d2_key -iv $encrypted_555d9b2948d2_iv
        -in client_secrets.json.enc -d | gcloud auth activate-service-account --key-file /dev/stdin
      script: ./scripts/deploy.sh

before_install:
  - |
    if [ ! -d $HOME/gcloud/google-cloud-sdk ]; then
        mkdir -p $HOME/gcloud
        wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz --directory-prefix=$HOME/gcloud
        cd $HOME/gcloud
        tar xzf google-cloud-sdk.tar.gz;
        ./google-cloud-sdk/install.sh -q;
        cd $TRAVIS_BUILD_DIR
    fi
  - source "$HOME/gcloud/google-cloud-sdk/path.bash.inc"
  - gcloud -q components update
  - gcloud -q version
  - wget --version
  - docker --version
  - docker-compose --version
