language: go
go:
- "1.x"
dist: trusty
services:
- docker-ce
cache:
  directories:
  - "$HOME/gcloud/"
env:
  global:
  - DOCKER_COMPOSE_VERSION="1.13.0"
  - PATH=$PATH:${HOME}/google-cloud-sdk/bin
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1

addons:
  apt:
    packages:
    - python3-pip

before_install:
  - if [ ! -d $HOME/gcloud/google-cloud-sdk ]; then
        mkdir -p $HOME/gcloud &&
        wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz --directory-prefix=$HOME/gcloud &&
        cd $HOME/gcloud &&
        tar xzf google-cloud-sdk.tar.gz &&
        printf '\ny\n\ny\ny\n' | ./google-cloud-sdk/install.sh &&
        cd $TRAVIS_BUILD_DIR;
    fi
  - gcloud -q components update
  - gcloud -q version

install:
  - gcloud -q components install kubectl
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - go get -t ./...

script:
  - go build ./...
  - gometalinter ./...
  - go test ./... -coverprofile=coverage1.txt
  - go test ./impl/integration/ -coverprofile=coverage2.txt -coverpkg=./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - pip3 install --user docker-compose
  - docker --version
  - docker-compose --version
  - openssl aes-256-cbc -K $encrypted_555d9b2948d2_key -iv $encrypted_555d9b2948d2_iv
    -in client_secrets.json.enc -out client_secrets.json -d
  - gcloud auth activate-service-account --key-file client_secrets.json
  - rm -f service_key.json
  - go get github.com/google/trillian/server/trillian_log_server
  - go get github.com/google/trillian/server/trillian_log_signer
  - go get github.com/google/trillian/server/trillian_map_server

deploy:
  skip_cleanup: true
  provider: script
  script: "./scripts/deploy.sh"
  on:
    branch: master
