language: go
go:
- "1.x"
dist: trusty
services:
- docker-ce
env:
  global:
  - DOCKER_COMPOSE_VERSION="1.13.0"
  - PATH=$PATH:${HOME}/google-cloud-sdk/bin
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1

addons:
  apt:
    sources:
    - google-cloud
    packages:
    - python3-pip
    - google-cloud-sdk
    - kubectl

before_install:
  - gcloud --quiet version
  - kubectl version
  - docker --version

install:
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install 
  - go get -t ./...

script:
  - go build ./...
  - gometalinter ./...
  - go test ./... -coverprofile=coverage1.txt
  - go test ./impl/integration/ -coverprofile=coverage2.txt -coverpkg=./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - pip3 install --user docker-compose
  - docker-compose --version
  - openssl aes-256-cbc -K $encrypted_a1eb99cfc21e_key -iv $encrypted_a1eb99cfc21e_iv -in travis_secrets.tar.gz.enc -out travis_secrets.tar.gz -d
  - tar -xzf travis_secrets.tar.gz
  - gcloud auth activate-service-account --key-file service_key.json
  - rm -f service_key.json
  - go get github.com/google/trillian/server/trillian_log_server
  - go get github.com/google/trillian/server/trillian_log_signer
  - go get github.com/google/trillian/server/trillian_map_server

deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy.sh
  on:
    branch: master
