version: "3"
services:
  prometheus:
    depends_on:
      - kt-server
      - kt-signer
    image: us.gcr.io/key-transparency/prometheus
    build:
      context: .
      dockerfile: deploy/prometheus/Dockerfile
    restart: always
    ports:
      - 9090:9090

  db:
    image: us.gcr.io/key-transparency/db
    build:
      context: ../.
      dockerfile: keytransparency/deploy/mysql-trillian/Dockerfile
    restart: always
    environment:
      MYSQL_PASSWORD: zaphod
      MYSQL_USER: test
      MYSQL_DATABASE: test
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

  trillian-log:
    depends_on:
      - db
    image: us.gcr.io/key-transparency/trillian_log_server
    build: 
      context: ../trillian
      dockerfile: server/trillian_log_server/Dockerfile
    restart: always
    ports:
      - "8090:8090" # gRPC
      - "8091:8091" # HTTP & Metrics
    environment:
      DB_HOST: db:3306
      DB_DATABASE: test
      DB_USER: test
      DB_PASSWORD: zaphod 

  trillian-log-signer:
    depends_on:
      - db
    image: us.gcr.io/key-transparency/trillian_log_signer
    build:
      context: ../trillian
      dockerfile: server/trillian_log_signer/Dockerfile
    restart: always
    ports:
      - "8092:8091" # HTTP & Metrics
    environment:
      DB_HOST: db:3306
      DB_DATABASE: test
      DB_USER: test
      DB_PASSWORD: zaphod
      SEQUENCER_INTERVAL: 1s


  trillian-map:
    depends_on:
      - db
    image: us.gcr.io/key-transparency/trillian_map_server
    build: 
      context: ../trillian
      dockerfile: server/trillian_map_server/Dockerfile
    restart: always
    ports:
      - "8093:8090" # gRPC
      - "8094:8091" # HTTP & Metrics
    environment:
      DB_HOST: db:3306
      DB_DATABASE: test
      DB_USER: test
      DB_PASSWORD: zaphod 

  kt-server:
    depends_on:
      - db
      - trillian-log
      - trillian-map
    build:
      context: ..
      dockerfile: ./keytransparency/cmd/keytransparency-server/Dockerfile
    image: us.gcr.io/key-transparency/keytransparency-server
    restart: always
    ports:
      - "8080:8080" # json & grpc
      - "8081:8081" # metrics
    environment:
      LOG_ID: ${LOG_ID} # Update with trillian admin CLI.
      LOG_URL: trillian-log:8090
      MAP_ID: ${MAP_ID} # Update with trillian admin CLI.
      MAP_URL: trillian-map:8090
      DB_HOST: db:3306
      DB_DATABASE: test
      DB_USER: test
      DB_PASSWORD: zaphod
      VRF_PRIV: /kt/vrf-key.pem
      VRF_PUB: /kt/vrf-pubkey.pem
      TLS_KEY_PATH: /kt/server.key
      TLS_CRT_PATH: /kt/server.crt
      VERBOSITY: 5

  kt-signer:
    depends_on:
      - db
      - trillian-log
      - trillian-map
    build:
      context: ..
      dockerfile: ./keytransparency/cmd/keytransparency-signer/Dockerfile
    image: us.gcr.io/key-transparency/keytransparency-signer
    restart: always
    environment:
      LOG_ID: ${LOG_ID} # Update with trillian admin CLI.
      LOG_URL: trillian-log:8090
      MAP_ID: ${MAP_ID} # Update with trillian admin CLI.
      MAP_URL: trillian-map:8090
      DB_HOST: db:3306
      DB_DATABASE: test
      DB_USER: test
      DB_PASSWORD: zaphod
      LOG_KEY: /kt/trillian-log.pem
      SIGN_KEY: /kt/p256-key.pem
      SIGN_KEY_PW: towel
      MIN_SIGN_PERIOD: 5s
      MAX_SIGN_PERIOD: 5m
      VERBOSITY: 5
