bases:
- ../../base
resources:
- managed-cert.yaml
patches:
- path: cloudsql-sidecar.yaml
  target:
    kind: Deployment
patchesStrategicMerge:
- ingress.yaml
- log-server-stackdriver-prometheus-sidecar.yaml
- log-signer-stackdriver-prometheus-sidecar.yaml
- map-server-stackdriver-prometheus-sidecar.yaml
- sequencer-stackdriver-prometheus-sidecar.yaml
- server-service.yaml
- server-stackdriver-prometheus-sidecar.yaml
