apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: log-signer
spec:
  template:
    spec:
      containers:
      - name: prometheus-to-sd
        image: gcr.io/google-containers/prometheus-to-sd:v0.2.6
        command:
          - /monitor
          - --stackdriver-prefix=custom.googleapis.com
          - --source=logsigner:http://localhost:8091/metrics
          - --pod-id=$(POD_NAME)
          - --namespace-id=$(POD_NAMESPACE)
          - --metrics-resolution=5s
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace

