apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: init
  name: init
spec:
  containers:
  - args:
    - sequencer:8080
    - --
    - curl
    - -k
    - https://sequencer:8080/v1/domains
    - -d{"domain_id":"default","min_interval":"1s","max_interval":"60s"}
    image: us.gcr.io/key-transparency/init:latest
    name: init
    resources: {}
  restartPolicy: OnFailure
status: {}
