apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../../docker-compose.yml
    kompose.version: 1.7.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: log-signer
  name: log-signer
spec:
  ports:
  - name: "8091"
    port: 8091
    targetPort: 8091
  selector:
    io.kompose.service: log-signer
status:
  loadBalancer: {}
