apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../../docker-compose.yml
    kompose.version: 1.4.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: log-server
  name: log-server
spec:
  ports:
  - name: "8090"
    port: 8090
    targetPort: 8090
  - name: "8091"
    port: 8091
    targetPort: 8091
  selector:
    io.kompose.service: log-server
status:
  loadBalancer: {}
