apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../../docker-compose.yml
    kompose.version: 1.4.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: log-server
  name: log-server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: log-server
    spec:
      containers:
      - command:
        - /go/bin/trillian_log_server
        - --mysql_uri=test:zaphod@tcp(db:3306)/test
        - --rpc_endpoint=0.0.0.0:8090
        - --http_endpoint=0.0.0.0:8091
        - --alsologtostderr
        image: us.gcr.io/key-transparency/log-server
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:8091/metrics
          failureThreshold: 3
          periodSeconds: 30
          timeoutSeconds: 30
        name: log-server
        ports:
        - containerPort: 8090
        - containerPort: 8091
        resources: {}
      restartPolicy: Always
status: {}
