apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../../docker-compose.yml
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: log-server
  name: log-server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: log-server
    spec:
      containers:
      - command:
        - /go/bin/trillian_log_server
        - --mysql_uri=test:zaphod@tcp(db:3306)/test
        - --rpc_endpoint=0.0.0.0:8090
        - --http_endpoint=0.0.0.0:8091
        - --alsologtostderr
        image: us.gcr.io/key-transparency/log-server:latest
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:8091/metrics
          failureThreshold: 3
          periodSeconds: 30
          timeoutSeconds: 30
        name: log-server
        ports:
        - containerPort: 8090
        - containerPort: 8091
        resources: {}
      - name: prometheus-to-sd
        image: gcr.io/google-containers/prometheus-to-sd:v0.2.6
        command:
          - /monitor
          - --stackdriver-prefix=custom.googleapis.com
          - --source=logserver:http://localhost:8091/metrics
          - --pod-id=$(POD_NAME)
          - --namespace-id=$(POD_NAMESPACE)
          - --metrics-resolution=5s
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      restartPolicy: Always
status: {}
