apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../../docker-compose.yml
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: log-signer
  name: log-signer
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: log-signer
    spec:
      containers:
      - name: trillian-logsigner
        args: [
        "--mysql_uri=test:zaphod@tcp(db:3306)/test",
        "--http_endpoint=0.0.0.0:8091",
        "--sequencer_guard_window=0s",
        "--sequencer_interval=1s",
        "--num_sequencers=1",
        "--batch_size=50",
        "--force_master=true",
        "--alsologtostderr"
        ]
        image: gcr.io/trillian-opensource-ci/log_signer:latest
        livenessProbe:
         httpGet:
           path: /metrics
           port: 8091
        name: log-signer
        ports:
        - containerPort: 8091
        resources: {}
      - name: prometheus-to-sd
        image: gcr.io/google-containers/prometheus-to-sd:v0.2.6
        command:
          - /monitor
          - --stackdriver-prefix=custom.googleapis.com
          - --source=logsigner:http://localhost:8091/metrics
          - --pod-id=$(POD_NAME)
          - --namespace-id=$(POD_NAMESPACE)
          - --metrics-resolution=5s
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      restartPolicy: Always
status: {}
