apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../../docker-compose.yml
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: sequencer
  name: sequencer
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sequencer
    spec:
      containers:
      - command:
        - /keytransparency-sequencer
        - --force_master
        - --db=test:zaphod@tcp(db:3306)/test
        - --addr=0.0.0.0:8080
        - --log-url=log-server:8090
        - --map-url=map-server:8090
        - --alsologtostderr
        - --v=5
        image: gcr.io/key-transparency/keytransparency-sequencer:latest
        livenessProbe:
         httpGet:
           path: /metrics
           port: 8081
        name: sequencer
        ports:
        - containerPort: 8080
        - containerPort: 8081
        resources: {}
      - name: prometheus-to-sd
        image: gcr.io/google-containers/prometheus-to-sd:v0.2.6
        command:
          - /monitor
          - --stackdriver-prefix=custom.googleapis.com
          - --source=sequencer:http://localhost:8081/metrics
          - --pod-id=$(POD_NAME)
          - --namespace-id=$(POD_NAMESPACE)
          - --metrics-resolution=5s
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      restartPolicy: Always
status: {}
