apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../../docker-compose.yml
    kompose.service.type: LoadBalancer
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      containers:
      - command:
        - /go/bin/keytransparency-server
        - --addr=0.0.0.0:8080
        - --db=test:zaphod@tcp(db:3306)/test
        - --log-url=log-server:8090
        - --map-url=map-server:8090
        - --tls-key=/kt/server.key
        - --tls-cert=/kt/server.crt
        - --auth-type=insecure-fake
        - --alsologtostderr
        - --v=5
        image: us.gcr.io/key-transparency/keytransparency-server:latest
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:8081/metrics
          failureThreshold: 5
          periodSeconds: 30
          timeoutSeconds: 10
        name: server
        ports:
        - containerPort: 8080
        - containerPort: 8081
        resources: {}
      - name: prometheus-to-sd
        image: gcr.io/google-containers/prometheus-to-sd:v0.2.6
        command:
          - /monitor
          - --stackdriver-prefix=custom.googleapis.com
          - --source=keyserver:http://localhost:8081/metrics
          - --pod-id=$(POD_NAME)
          - --namespace-id=$(POD_NAMESPACE)
          - --metrics-resolution=5s
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      restartPolicy: Always
status: {}
